export type WeightOption = { label: string; price: number | null };
export type Product = {
  id: number;
  name: string;
  name_hi: string;
  slug: string;
  category: string;
  short_description: string;
  description: string;
  description_hi: string;
  price: number | null;
  show_price: number;
  unit: string;
  ingredients: string;
  shelf_life: string;
  contains_nuts: number;
  weights_json: string;
  badge: string;
  sort_order: number;
  enquiry_count: number;
  image_url: string;
  gallery: string[];
  available: number;
  featured: number;
  published: number;
  created_at?: string;
};
export type ProductInput = Omit<Product, "id" | "created_at" | "enquiry_count">;
export type ShopSettings = Record<string, string> & { whatsapp: string; shopName: string; categories?: string };
